// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../scripts/app.js', ['chapter2.App'], ['goog.fx.Dragger', 'goog.ui.HsvPalette']);
