// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../scripts/app.js', ['tinyword.App'], ['goog.ds.DataManager', 'goog.ds.JsDataSource', 'goog.events.EventHandler']);
