// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../scripts/app.js', ['tinyword.App'], ['goog.dom.ViewportSizeMonitor', 'goog.ds.DataManager', 'goog.ds.JsDataSource', 'goog.events.EventHandler', 'goog.ui.SplitPane', 'tinyword.LeftPane', 'tinyword.RightPane']);
goog.addDependency('../../../scripts/leftpane.js', ['tinyword.LeftPane'], ['goog.array', 'goog.dom.classes', 'goog.ui.Component', 'goog.ui.Menu', 'goog.ui.MenuItem', 'goog.ui.PopupMenu', 'goog.ui.Toolbar', 'goog.ui.ToolbarMenuButton', 'tinyword.TreeControl']);
goog.addDependency('../../../scripts/rightpane.js', ['tinyword.RightPane'], ['goog.array', 'goog.ui.Component', 'goog.ui.Tab', 'goog.ui.TabBar']);
goog.addDependency('../../../scripts/treecontrol.js', ['tinyword.TreeControl'], ['goog.array', 'goog.ds.DataManager', 'goog.ds.Expr', 'goog.functions', 'goog.object', 'goog.string', 'goog.ui.tree.TreeControl', 'tinyword.TreeNode']);
goog.addDependency('../../../scripts/treenode.js', ['tinyword.TreeNode'], ['goog.functions', 'goog.string', 'goog.ui.tree.TreeNode']);
